db:
- host: 172.23.28.24
  port: 28286
  path: db4
- host: 172.26.1.213
  path: db1
  port: 28283
  config:
    -default_logical_room: 'wx'
    -default_physical_room: 'wx1' 
- host: 172.26.1.214
  path: db1
  port: 28283
- host: 172.24.64.74
  path: db1
  port: 28283
- host: 172.24.64.20
  path: db1
  port: 28283
- host: 172.30.106.192
  path: db1
  port: 28283
- host: 172.30.106.193
  path: db1
  port: 28283
global:
  cluster: trainDoubleCenter
  root_dir: /home/work/BaikalDB
  version: v2.0.2
meta:
- host: 172.24.64.20
  path: meta
  port: 8010
- host: 172.26.1.214
  path: meta
  port: 8010
- host: 172.30.106.193
  path: meta
  port: 8010
