#!/bin/bash

self_port=`grep port ../conf/gflags.conf | awk -F"=" '{print $2}'|sed 's/ //g'`
echo "Restart... $(date) " >> restart.log
export TCMALLOC_SAMPLE_PARAMETER=524288
export TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES=209715200
ulimit -u 10240
ulimit -c unlimited
cpu_cores=__CPU_CORES_LIST__
#mem_limit=__MEM_LIMIT__
#ulimit -v $mem_limit
sleep 5
cd .. && nohup taskset -c $cpu_cores ./bin/baikalMeta global:$self_port
