db:
- config:
    -disambiguate_select_name: 'true'
    -print_time_us: '10'
    -query_quota_per_user: '30000'
    -schema_ignore_case: 'false'
  host: 10.100.217.149
  path: db
  port: 28282
- host: 10.100.217.152
  port: 28282
global:
  cluster: devnew
  root_dir: /home/work/BaikalDB
  version: v2.0.0.3
meta:
- host: 10.100.217.149
  path: meta
  port: 8010
- host: 10.100.217.150
  path: meta
  port: 8010
- host: 10.100.217.151
  path: meta
  port: 8010
server_configs:
  meta:
    -ddl_update_time: '60000000'
    -enable_debug: 'true'
    -enable_self_trace: 'false'
    -table_tombstone_gc_time_s: '172800'
  store:
    -default_logical_room: sz
    -default_physical_room: sz1
    -print_time_us: '0'
    -resource_tag: normal
    -rocks_block_cache_size_mb: '4096'
store:
- host: 10.100.217.151
  path: store
  port: 8110
- host: 10.100.217.154
  path: store
  port: 8110
- host: 10.100.217.150
  path: store
  port: 8110
- host: 10.100.217.152
  path: store
  port: 8110
- host: 10.100.217.149
  path: store
  port: 8110
